### ISSUE TITLE
cpp data quality, exposing henkel matrix.

### ISSUE THREAD

**Issue by marvin-ad-martianum** [dominichofer/DeePC#26]
its very difficult to asses data quality in this case. however, for any usable implementation i will need some checks. therefore condition number, rank and singular values of the core matrices are important nrs to be able to calculate in cpp and python. therefore i suggest either adding this functionality or exposing these matrices such that i can add the code externally.

**Comment by dominichofer** [comment]
Would https://github.com/dominichofer/DeePC/pull/27 give you sufficient access to the matrix?

**Comment by marvin-ad-martianum** [comment]
maybe do it with the four matrices. i gave an example of two heuristics and important checks on the commit https://github.com/dominichofer/DeePC/commit/4c49f7d2caa17a7ca9b308deeb294739d706031c

i will need to do some analysis of this sort before i deploy a controller.

**Comment by dominichofer** [comment]
The lifetimes of the matrices Up, U_f, Y_p, Y_f are limited to the scope of the constructor of the controller; see https://github.com/dominichofer/DeePC/blob/main/src/deepcpp/controller.cpp#L67-L72 .
Promoting them to members of the controller would impose a memory overhead on the controller.
But you can compute the matrices yourself outside the constructor of the controller and then inspect their values, like so
```
    auto U = HankelMatrix(T_ini + target_size, u_d);
    auto U_p = U.block(0, 0, T_ini * input_dims, U.cols()); // past
    auto U_f = U.block(T_ini * input_dims, 0, U.rows() - T_ini * input_dims, U.cols()); // future
    auto Y = HankelMatrix(T_ini + target_size, y_d);
    auto Y_p = Y.block(0, 0, T_ini * output_dims, Y.cols()); // past
    auto Y_f = Y.block(T_ini * output_dims, 0, Y.rows() - T_ini * output_dims, Y.cols()); // future
```

**Comment by marvin-ad-martianum** [comment]
good idea.
